### ISSUE TITLE
[Bug]: `wait.ForLog.WithStartupTimeout` affects container startup time

### ISSUE THREAD

**Issue by kriswuollett** [testcontainers/testcontainers-go#1043]
### Testcontainers version

0.19.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86_64

### Go version

1.20

### Docker version

```shell
Client:
 Version:           20.10.23+azure-2
 API version:       1.41
 Go version:        go1.19.6
 Git commit:        715524332ff91d0f9ec5ab2ec95f051456ed1dba
 Built:             Wed Jan 18 20:42:16 UTC 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.23+azure-3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.6
  Git commit:       5d6db842238e3c4f5f9fb9ad70ea46b35227d084
  Built:            Tue Apr  4 18:03:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20+azure-1
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        f19387a6bec4944c770f7668ab51c4348d9c2f38
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.4)
  compose: Docker Compose (Docker Inc., 2.17.2+azure-1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 20.10.23+azure-3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: f19387a6bec4944c770f7668ab51c4348d9c2f38
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-32-generic
 Operating System: Debian GNU/Linux 11 (bullseye) (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 48
 Total Memory: 125.5GiB
 Name: 2e7d44ba9ab3
 ID: 3MXX:ZIBI:AYTM:PTXK:K5WS:HUA5:4DDY:4JE3:VMZK:YLSI:S4VN:5MX3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Test times out when using `wait.ForLog("database system is ready to accept connections").WithStartupTimeout(1 * time.Minute)` when testing with option `-timeout 1m`, however without the wait check, the test passes in 1.806s.

### Relevant log output

```shell
Running tool: /usr/local/go/bin/go test -timeout 1m -run ^TestWithPostgres$ [REDACTED]

2023/04/12 18:13:10 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 20.10.23+azure-3
  API Version: 1.41
  Operating System: Debian GNU/Linux 11 (bullseye) (containerized)
  Total Memory: 128527 MB
2023/04/12 18:13:10 Starting container id: 7fb73b03eb82 image: docker.io/testcontainers/ryuk:0.3.4
2023/04/12 18:13:10 Waiting for container id 7fb73b03eb82 image: docker.io/testcontainers/ryuk:0.3.4
2023/04/12 18:13:11 Container is ready id: 7fb73b03eb82 image: docker.io/testcontainers/ryuk:0.3.4
2023/04/12 18:13:11 Starting container id: dfa701f15d38 image: postgres:14
2023/04/12 18:13:11 Waiting for container id dfa701f15d38 image: postgres:14
panic: test timed out after 1m0s
running tests:
	TestWithPostgres (1m0s)

goroutine 692 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001a49c0, {0xb6f7f8?, 0x527d65?}, 0xbb14a0)
	/usr/local/go/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x108e8a0?)
	/usr/local/go/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc0001a49c0, 0xc00035fc88)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc000438140?, {0x1077a20, 0x1, 0x1}, {0x20?, 0x100c00018db48?, 0x108de80?})
	/usr/local/go/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc000438140)
	/usr/local/go/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:47 +0x1aa

goroutine 6 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/go/src/runtime/time.go:195 +0x135
github.com/testcontainers/testcontainers-go/wait.(*LogStrategy).WaitUntilReady(0xc000315800, {0xc59970?, 0xc00003e080?}, {0xc5a958, 0xc0004386e0})
	/home/vscode/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.19.0/wait/log.go:106 +0x166
github.com/testcontainers/testcontainers-go.(*DockerContainer).Start(0xc0004386e0, {0xc59970, 0xc00003e080})
	/home/vscode/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.19.0/docker.go:202 +0x24f
[REDACTED].TestWithPostgres(0xc0001a4b60)
	/workspaces/code/[REDACTED]_test.go:43 +0x34a
testing.tRunner(0xc0001a4b60, 0xbb14a0)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7f4ce0d10818, 0x72)
	/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000379f00?, 0xc00043d000?, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000379f00, {0xc00043d000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
net.(*netFD).Read(0xc000379f00, {0xc00043d000?, 0x43c0e7?, 0xc0000d0c30?})
	/usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000014480, {0xc00043d000?, 0x0?, 0xc0004d9520?})
	/usr/local/go/src/net/net.go:183 +0x45
net/http.(*persistConn).Read(0xc0001a7c20, {0xc00043d000?, 0xc00010e000?, 0xc0000d0d30?})
	/usr/local/go/src/net/http/transport.go:1943 +0x4e
bufio.(*Reader).fill(0xc0000eeba0)
	/usr/local/go/src/bufio/bufio.go:106 +0xff
bufio.(*Reader).Peek(0xc0000eeba0, 0x1)
	/usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc0001a7c20)
	/usr/local/go/src/net/http/transport.go:2107 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1765 +0x16ea

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc0001a7c20)
	/usr/local/go/src/net/http/transport.go:2410 +0xf2
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1766 +0x173d

goroutine 60 [chan receive]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1({0xc5c108?, 0xc000014288})
	/home/vscode/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.19.0/reaper.go:193 +0x7d5
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/home/vscode/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.19.0/reaper.go:158 +0x195
FAIL	[REDACTED]	60.025s
FAIL
```

### Additional information

Output from starting up `postgres:14` from the command line:

```shell
$ docker run --rm -p 5432 -e POSTGRES_PASSWORD=foo postgres:14
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2023-04-12 17:57:37.952 UTC [48] LOG:  starting PostgreSQL 14.7 (Debian 14.7-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-04-12 17:57:37.958 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-04-12 17:57:37.987 UTC [49] LOG:  database system was shut down at 2023-04-12 17:57:37 UTC
2023-04-12 17:57:38.001 UTC [48] LOG:  database system is ready to accept connections
 done
server started

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2023-04-12 17:57:38.162 UTC [48] LOG:  received fast shutdown request
waiting for server to shut down....2023-04-12 17:57:38.169 UTC [48] LOG:  aborting any active transactions
2023-04-12 17:57:38.172 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
2023-04-12 17:57:38.173 UTC [50] LOG:  shutting down
2023-04-12 17:57:38.252 UTC [48] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2023-04-12 17:57:38.321 UTC [1] LOG:  starting PostgreSQL 14.7 (Debian 14.7-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-04-12 17:57:38.321 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-04-12 17:57:38.321 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-04-12 17:57:38.334 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-04-12 17:57:38.350 UTC [61] LOG:  database system was shut down at 2023-04-12 17:57:38 UTC
2023-04-12 17:57:38.366 UTC [1] LOG:  database system is ready to accept connections
```

Test file:

```go
package main

import (
	"context"
	"testing"
	"time"

	"github.com/docker/docker/api/types/container"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

type MyLogger struct {
	t *testing.T
}

func (l *MyLogger) Accept(event testcontainers.Log) {
	l.t.Log(string(event.Content))
}

func TestWithPostgres(t *testing.T) {
	logger := MyLogger{
		t: t,
	}
	ctx := context.Background()
	req := testcontainers.ContainerRequest{
		Image:        "postgres:14",
		ExposedPorts: []string{"5432/tcp"},
		Cmd:        []string{"postgres", "-c", "fsync=off"},
		HostConfigModifier: func(hc *container.HostConfig) {
			hc.AutoRemove = false
		},
		WaitingFor: wait.ForLog("database system is ready to accept connections").WithStartupTimeout(1 * time.Minute),
	}
	postgresC, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
	})
	if err != nil {
		t.Error(err)
	}

	postgresC.FollowOutput(&logger)
	postgresC.Start(ctx)

	defer func() {
		if err := postgresC.Terminate(ctx); err != nil {
			t.Fatalf("failed to terminate container: %s", err.Error())
		}
	}()
}
```

**Comment by kriswuollett** [comment]
The problem seems to be `WithPollInterval` doesn't have the expected affect, which by default is 100ms it seems. My test was failing above because `WithStartupTimeout` literally caused the container to take 1 minute to be considered started up which was my test timeout from vscode.

Using the following causes my test to finish in 11s:

`WaitingFor: wait.ForLog("database system is ready to accept connections").WithOccurrence(2).WithStartupTimeout(10 * time.Second),`

But using the following causes my test to finish in 4.5s:

`WaitingFor: wait.ForLog("database system is ready to accept connections").WithOccurrence(2).WithStartupTimeout(3 * time.Second),`

**Comment by kriswuollett** [comment]
This is probably a separate issue, but the following causes my test the pass in just under 5s, but shouldn't because that log should have only printed twice by `postgres`:

WaitingFor: wait.ForLog("database system is ready to accept connections").WithOccurrence(10).WithStartupTimeout(3 * time.Second),

**Comment by kriswuollett** [comment]
Was use error since was not able to debug container startup since did not startup the log producer to find out about the error that was being produced that I did not check in starting the container (no `POSTGRES_PASSWORD` env var).

**Comment by mdelapenya** [comment]
Thanks @kriswuollett for reporting, checking and closing the issue. I'm preparing a talk for the end of this week and postponed commenting here. 🙏
