### ISSUE TITLE
[Bug]: failing to connect to Container while on Github Actions

### ISSUE THREAD

**Issue by dcfranca** [testcontainers/testcontainers-go#1363]
### Testcontainers version

0.21.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### Go version

1.19.2

### Docker version

```shell
Client:
 Version:           20.10.25+azure-2
 API version:       1.41
 Go version:        go1.19.10
 Git commit:        b82b9f3a0e763304a250531cb9350aa6d93723c9
 Built:             Thu Apr  6 10:55:17 UTC 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.25+azure-2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.10
  Git commit:       5df983c7dbe2f8914e6efd4dd6e0083a20c41ce1
  Built:            Thu May  4 13:33:05 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21+azure-1
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### Docker info

```shell
Run docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., 0.11.1+azure-1)
  compose: Docker Compose (Docker Inc., 2.19.1+azure-1)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 20.10.25+azure-2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1041-azure
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.769GiB
 Name: fv-az268-698
 ID: R6HY:WYAJ:TMR5:SJCI:A3KT:ZR2V:2JFR:OMUR:D6AS:HXPR:WY6M:2N4K
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: githubactions
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

The tests work flawless when I run it locally (MacOS ARM64), but fails to connect to the database when running on a CI pipeline in Github Actions

The error
```
2023/07/17 18:56:14 mysql container ready and running at port:  32780/tcp
2023/07/17 18:56:14 Connection String:  root:password@tcp(localhost:32780)/docdep?tls=skip-verify
[mysql] 2023/07/17 18:56:14 packets.go:37: unexpected EOF
[mysql] 2023/07/17 18:56:14 packets.go:37: unexpected EOF
[mysql] 2023/07/17 18:56:14 packets.go:37: unexpected EOF
2023/07/17 18:56:14 error pinging db: driver: bad connection
```

I have tried setting `NetworkMode` to `"host"` without success:
e.g:
```go
	req := testcontainers.ContainerRequest{
		Image:        "mysql:latest",
		ExposedPorts: []string{"6605/tcp"},
		Env:          env,
		NetworkMode:  "host",
		WaitingFor:   wait.ForListeningPort("6605/tcp").WithStartupTimeout(time.Minute * 2),
	}

```

### Relevant log output

```shell
goroutine 28 [running]:
testing.tRunner.func1.2({0xd15960, 0xc00004f570})
	/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1399 +0x39f
panic({0xd15960, 0xc00004f570})
	/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212
log.Panicf({0xe7efb3?, 0x1194658?}, {0xc000667418?, 0x39?, 0x5?})
	/opt/hostedtoolcache/go/1.19.2/x64/src/log/log.go:395 +0x67
docdep-backend/utils.CreateTestContainer({0x1194658, 0xc00012e000}, {0xe71183, 0x6})
	/home/runner/work/docdep-backend/docdep-backend/utils/test.go:81 +0x8bb
docdep-backend/utils.InitializeTestDatabase(0xc00049e9c0, 0x0)
	/home/runner/work/docdep-backend/docdep-backend/utils/test.go:204 +0x48
docdep-backend/api/groupMembers.TestCreateGroupMember(0xc00049e9c0)
	/home/runner/work/docdep-backend/docdep-backend/api/groupMembers/handlers_test.go:89 +0x46
testing.tRunner(0xc00049e9c0, 0xeccbe0)
	/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.2/x64/src/testing/testing.go:1493 +0x35f
FAIL	docdep-backend/api/groupMembers	34.486s
```

### Additional information

The container creation function
```go
func CreateTestContainer(ctx context.Context, dbname string) (testcontainers.Container, *sql.DB, error) {
	var env = map[string]string{
		"MYSQL_ROOT_PASSWORD": "password",
		"MYSQL_DATABASE":      dbname,
		"MYSQL_TCP_PORT":      "6605",
	}
	var port = "6605/tcp"

	log.Println("Requesting container...")

	req := testcontainers.ContainerRequest{
		Image:        "mysql:latest",
		ExposedPorts: []string{"6605/tcp"},
		Env:          env,
		// WaitingFor:   wait.ForLog("port: 6605  MySQL Community Server - GPL"),
		WaitingFor: wait.ForListeningPort("6605/tcp").WithStartupTimeout(time.Minute * 2),
	}

	log.Println("Creating container...")
	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	if err != nil {
		return container, nil, fmt.Errorf("failed to start container: %s", err)
	}

	log.Println("Mapping port...")
	mappedPort, err := container.MappedPort(ctx, nat.Port(port))
	if err != nil {
		return container, nil, fmt.Errorf("failed to get container external port: %s", err)
	}

	log.Println("mysql container ready and running at port: ", mappedPort)

	host, _ := container.Host(ctx)
	p, _ := container.MappedPort(ctx, "6605/tcp")
	portI := p.Int()
	connectionString := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?tls=skip-verify",
		"root", "password", host, portI, dbname)

	log.Println("Connection String: ", connectionString)

	db, _ := sql.Open("mysql", connectionString)
	if err = db.Ping(); err != nil {
		log.Panicf("error pinging db: %+v\n", err)
	}

	// Read the contents of the init.sql file
	file, err := os.Open("../../init.sql")
	if err != nil {
		return container, db, fmt.Errorf("failed to open SQL file: %s", err)
	}
	defer file.Close()

	// Split the contents of the file into separate SQL commands
	scanner := bufio.NewScanner(file)
	var sb strings.Builder
	for scanner.Scan() {
		line := scanner.Text()
		line = strings.TrimSpace(line)
		if len(line) == 0 || strings.HasPrefix(line, "--") {
			continue
		}
		sb.WriteString(line)
		sb.WriteString(" ")
		if strings.HasSuffix(line, ";") {
			query := sb.String()
			sb.Reset()
			_, err = db.Exec(query)
			if err != nil {
				return container, db, fmt.Errorf("failed to execute SQL query: %s, error: %s", query, err)
			}
		}
	}
	if err = scanner.Err(); err != nil {
		return container, db, fmt.Errorf("failed to read SQL file: %s", err)
	}

	fmt.Println("Success created container")

	return container, db, nil
}
```

The Makefile
```
build:
	docker build .
run:
	docker-compose up --build
stop:
	docker-compose down
test:
	go test -mod=vendor -v ./...
```

The Github workflow
```
name: Backend Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.2'

    - name: Show Docker version
      run: docker version

    - name: Show Docker info
      run: docker info

    - name: Run tests
      run: make test
```

**Comment by saryani** [comment]
I have similar issue even with older versions of testcontainers-go
I tested it with all versions from 0.19.0 -> current versions
I also got the same error on my local machine which is a mac m1
My docker runtime environment is colima, but I also tried testing with rancher desktop and the errors were exactly the same:

this is the error message i get when I run the tests:

```bash
2023/07/21 11:01:06 github.com/testcontainers/testcontainers-go - Connected to docker:
  Server Version: 23.0.6
  API Version: 1.42
  Operating System: Alpine Linux v3.18
  Total Memory: 1971 MB
2023/07/21 11:01:06 🐳 Creating container for image docker.io/testcontainers/ryuk:0.5.1
2023/07/21 11:01:06 ✅ Container created: a6cbf694e8b5
2023/07/21 11:01:06 🐳 Starting container: a6cbf694e8b5
2023/07/21 11:01:06 ✅ Container started: a6cbf694e8b5
2023/07/21 11:01:06 🚧 Waiting for container id a6cbf694e8b5 image: docker.io/testcontainers/ryuk:0.5.1. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2023/07/21 11:01:06 failed accessing container logs: %!w(errdefs.errNotFound={0x140004ad3c8})
    wizard_integration_test.go:372:
                Error Trace:    /Users/XXX/Projects/XXX/pensive/wizard/integration/wizard/wizard_integration_test.go:372
                                                        /Users/XXX/Projects/XXX/pensive/wizard/integration/wizard/wizard_integration_test.go:46
                                                        /Users/XXX/.go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:154
                                                        /Users/XXX/Projects/XXX/pensive/wizard/integration/wizard/wizard_integration_test.go:403
                Error:          Received unexpected error:
                                unexpected container status "removing": could not start container: creating reaper failed: failed to create container
                Test:           TestSuiteIntegration
--- FAIL: TestSuiteIntegration (0.54s)
```

**Comment by Or-Geva** [comment]
Same problem for me.

**Comment by nerdalert** [comment]
fwiw, I resolved the issue by pinning the following docker commit:

```
github.com/docker/docker v24.0.5-0.20230714235725-36e9e796c6fc+incompatible
```

Full go.mod https://github.com/nexodus-io/nexodus/blob/main/go.mod

Cheers

**Comment by silverspace** [comment]
I am not an author, but I suspect your issue is with the usage of `wait.ForListeningPort("6605/tcp")` rather than `wait.ForLog("port: 3306  MySQL Community Server")`. 

See the testcontainers-go mysql module for reference: https://github.com/testcontainers/testcontainers-go/blob/main/modules/mysql/mysql.go#L57C65-L57C65

I saw this issue with postgres as well, since the port is bound long before the service is actually ready to service requests. In the case of postgres, the service actually starts up twice in `entrypoint.sh`, requiring `wait.ForLog("database system is ready to accept connections").WithOccurrence(2)` to wait properly.

**Comment by dcfranca** [comment]
@silverspace It worked! Thanks

**Comment by mdelapenya** [comment]
Thank you all for helping each other!

Great community work 👏👏
