### ISSUE TITLE
failed to start container: context deadline exceeded

### ISSUE THREAD

**Issue by fwilhe** [testcontainers/testcontainers-go#157]
**Describe the bug**
Not sure if it is a bug. I'm trying to start a nexus container for integration testing of nexus upload functionality and it takes longer then one minute to start.

Running my test results in this output:

```
go test ./integration
2020/02/18 18:23:43 Starting container id: db9d12669ea2 image: quay.io/testcontainers/ryuk:0.2.3
2020/02/18 18:23:43 Container is ready id: db9d12669ea2 image: quay.io/testcontainers/ryuk:0.2.3
2020/02/18 18:23:43 Starting container id: 257c9583ef19 image: sonatype/nexus3:3.14.0
2020/02/18 18:23:44 Waiting for container id 257c9583ef19 image: sonatype/nexus3:3.14.0
--- FAIL: TestNexusUpload (61.77s)
    integration_nexus_upload_test.go:25: failed to start container: context deadline exceeded
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1472379]

goroutine 7 [running]:
testing.tRunner.func1(0xc0000e9300)
	/usr/local/Cellar/go/1.13.8/libexec/src/testing/testing.go:874 +0x3a3
panic(0x14f4760, 0x196ddd0)
	/usr/local/Cellar/go/1.13.8/libexec/src/runtime/panic.go:679 +0x1b2
github.com/SAP/jenkins-library/integration.TestNexusUpload(0xc0000e9300)
	/Users/d071222/code/gh-com/jenkins-library/integration/integration_nexus_upload_test.go:37 +0x569
testing.tRunner(0xc0000e9300, 0x15a7468)
	/usr/local/Cellar/go/1.13.8/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.8/libexec/src/testing/testing.go:960 +0x350
FAIL	github.com/SAP/jenkins-library/integration	62.105s
FAIL
```

I am not sure what _context deadline exceeded_ refers to. Is it the context in my test code, or some docker internal thing?

**To Reproduce**
Can you write a unit test to reproduce your issue?

Full code of `integration_nexus_upload_test.go`

```
package main

import (
	"context"
	"fmt"
	"net/http"
	"testing"

	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func TestNexusUpload(t *testing.T) {
	ctx := context.Background()
	req := testcontainers.ContainerRequest{
		Image:        "sonatype/nexus3:3.14.0",
		ExposedPorts: []string{"8081/tcp"},
		WaitingFor:   wait.ForLog("Started Sonatype Nexus"),
	}
	nexusContainer, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	if err != nil {
		t.Error(err)
	}
	defer nexusContainer.Terminate(ctx)
	ip, err := nexusContainer.Host(ctx)
	if err != nil {
		t.Error(err)
	}
	port, err := nexusContainer.MappedPort(ctx, "8081")
	if err != nil {
		t.Error(err)
	}
	resp, err := http.Get(fmt.Sprintf("http://%s:%s", ip, port.Port()))
	if resp.StatusCode != http.StatusOK {
		t.Errorf("Expected status code %d. Got %d.", http.StatusOK, resp.StatusCode)
	}
}
```

The whole code is available here https://github.com/SAP/jenkins-library/tree/nexus-upload/integration

**Expected behavior**

The nexus container is started no matter how long it takes and I can write tests against it.

** docker info **
output of the command:

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 70
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4.825GiB
 Name: docker-desktop
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 37
  Goroutines: 56
  System Time: 2020-02-18T17:28:28.8407643Z
  EventsListeners: 5
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

**Additional context**

I tried different contexts, with Timeout, with cancel etc. I had it "working" at some point so the given code was running without an error, I'm not sure what changed. Also I have to say I'm new to go, so maybe I miss something really obvious.

**Comment by ClaytonNorthey92** [comment]
Thanks for the detailed description!

It sounds like the container you are starting doesn't output the log "Started Sonatype Nexus"  within the default timeout, which is 1 minute.

If your container takes longer than that to log out the message, I would suggest increasing the timeout like so...
```go
wait.ForLog("Started Sonatype Nexus").WithStartupTimeout(time.Minute * n) // where n is the number of minutes to wait, greater than 1
```

if you are still getting failures, I would inspect the container logs and see what it is logging out

does this help?

**Comment by fwilhe** [comment]
Oh, that seems to resolve the issue. I misunderstood the API. I guess `context deadline exceeded` mislead me to think I need to change the `ctx`. Thanks for your quick help 👍
