### ISSUE TITLE
[Bug]: write to kafka failed

### ISSUE THREAD

**Issue by bigwhite** [testcontainers/testcontainers-go#1997]
### Testcontainers version

v0.26.0

### Using the latest Testcontainers version?

Yes

### Host OS

linux

### Host arch

amd64

### Go version

go1.21.4

### Docker version

```shell
Docker version 24.0.7, build afdd53b
```

### Docker info

```shell
docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 16
  Running: 0
  Paused: 0
  Stopped: 16
 Images: 10
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 3.10.0-1160.95.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.26GiB
 Name: iZ2ze18rmx2avqb5xgb4omZ
 ID: d203a228-b46a-43d5-9652-ad8cc27c00d4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

I wrote a test with testcontainer kafka module, but I got error when testcase write to the successully startup kafka container，the below is my test code:

```
package main

import (
	"context"
	"errors"
	"net"
	"strconv"
	"testing"
	"time"

	"github.com/testcontainers/testcontainers-go/modules/kafka"

	kc "github.com/segmentio/kafka-go" // kafka client
)

func createTopics(brokers []string, topics ...string) error {
	// to create topics when auto.create.topics.enable='false'
	conn, err := kc.Dial("tcp", brokers[0])
	if err != nil {
		return err
	}
	defer conn.Close()

	controller, err := conn.Controller()
	if err != nil {
		return err
	}
	var controllerConn *kc.Conn
	controllerConn, err = kc.Dial("tcp", net.JoinHostPort(controller.Host, strconv.Itoa(controller.Port)))
	if err != nil {
		return err
	}
	defer controllerConn.Close()

	var topicConfigs []kc.TopicConfig
	for _, topic := range topics {
		topicConfig := kc.TopicConfig{
			Topic:             topic,
			NumPartitions:     1,
			ReplicationFactor: 1,
		}
		topicConfigs = append(topicConfigs, topicConfig)
	}

	err = controllerConn.CreateTopics(topicConfigs...)
	if err != nil {
		return err
	}

	return nil
}

func newWriter(brokers []string, topic string) *kc.Writer {
	return &kc.Writer{
		Addr:                   kc.TCP(brokers...),
		Topic:                  topic,
		Balancer:               &kc.LeastBytes{},
		AllowAutoTopicCreation: true,
		RequiredAcks:           0,
	}
}

func newReader(brokers []string, topic string) *kc.Reader {
	return kc.NewReader(kc.ReaderConfig{
		Brokers:  brokers,
		Topic:    topic,
		GroupID:  "test-group",
		MaxBytes: 10e6, // 10MB
	})
}

func TestProducerAndConsumer(t *testing.T) {
	ctx := context.Background()

	kafkaContainer, err := kafka.RunContainer(ctx, kafka.WithClusterID("test-cluster"))
	if err != nil {
		t.Fatalf("want nil, actual %v\n", err)
	}

	// Clean up the container
	defer func() {
		if err := kafkaContainer.Terminate(ctx); err != nil {
			t.Fatalf("want nil, actual %v\n", err)
		}
	}()

	state, err := kafkaContainer.State(ctx)
	if err != nil {
		t.Fatalf("want nil, actual %v\n", err)
	}

	if state.Running != true {
		t.Errorf("want true, actual %t", state.Running)
	}

	brokers, err := kafkaContainer.Brokers(ctx)
	if err != nil {
		t.Fatalf("want nil, actual %v\n", err)
	}

	topic := "test-topic"
	w := newWriter(brokers, topic)
	defer w.Close()
	r := newReader(brokers, topic)
	defer r.Close()

	messages := []kc.Message{
		{
			Key:   []byte("Key-A"),
			Value: []byte("Hello World!"),
		},
		{
			Key:   []byte("Key-B"),
			Value: []byte("One!"),
		},
		{
			Key:   []byte("Key-C"),
			Value: []byte("Two!"),
		},
	}

	const retries = 3
	for i := 0; i < retries; i++ {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		// attempt to create topic prior to publishing the message
		err = w.WriteMessages(ctx, messages...)
		if errors.Is(err, kc.LeaderNotAvailable) || errors.Is(err, context.DeadlineExceeded) {
			time.Sleep(time.Millisecond * 250)
			continue
		}

		if err != nil {
			t.Fatalf("want nil, actual %v\n", err)
		}
		break
	}

	m, err := r.ReadMessage(context.Background())
	if err != nil {
		t.Fatalf("want nil, actual %v\n", err)
	}

	if string(m.Key) != "Key-A" {
		t.Errorf("want %s, actual %s\n", "Key-A", string(m.Key))
	}
}
```

### Relevant log output

```shell
# go test
2023/12/17 09:37:54 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.7
  API Version: 1.43
  Operating System: CentOS Linux 7 (Core)
  Total Memory: 30984 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 70f387b5fa85f84d7753a8c34441f18253833a40063fec4247b67b2884211b1d
  Test ProcessID: 0830d04a-e98c-4ac4-a6ed-ce77dc4617ad
2023/12/17 09:37:54 🐳 Creating container for image docker.io/testcontainers/ryuk:0.5.1
2023/12/17 09:37:55 ✅ Container created: dd20a3aa272f
2023/12/17 09:37:55 🐳 Starting container: dd20a3aa272f
2023/12/17 09:37:55 ✅ Container started: dd20a3aa272f
2023/12/17 09:37:55 🚧 Waiting for container id dd20a3aa272f image: docker.io/testcontainers/ryuk:0.5.1. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2023/12/17 09:37:55 🐳 Creating container for image confluentinc/confluent-local:7.5.0
2023/12/17 09:37:55 ✅ Container created: 500c1571ff4f
2023/12/17 09:37:55 🐳 Starting container: 500c1571ff4f
2023/12/17 09:37:55 ✅ Container started: 500c1571ff4f
2023/12/17 09:38:00 🐳 Terminating container: 500c1571ff4f
2023/12/17 09:38:01 🚫 Container terminated: 500c1571ff4f
--- FAIL: TestProducerAndConsumer (6.33s)
    kafka_test.go:135: want nil, actual [3] Unknown Topic Or Partition: the request is for a topic or partition that does not exist on this broker
FAIL
exit status 1
FAIL	demo	6.358s

```
```


### Additional information

I got the error log inside the container:

```

[2023-12-17 01:17:03,996] INFO [GroupCoordinator 1]: Assignment received from leader demo.test@iZ2ze18rmx2avqb5xgb4omZ (github.com/segmentio/kafka-go)-930da308-28bb-4ad9-837a-918578efae30 for group test-group for generation 1. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
Error while getting broker list.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
    at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
    at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
    at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
    at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:147)
    at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:149)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
Expected 1 brokers but found only 0. Trying to query Kafka for metadata again ...
Expected 1 brokers but found only 0. Brokers found [].
Error: kafka-ready check failed
Usage:
  ub kafka-ready <min-num-brokers> <timeout-secs> [flags]
```

**Comment by bigwhite** [comment]
It is not a bug! topic creating need more time. When I add more wait time after writing to kafka, the test passed!
