### ISSUE TITLE
[Bug]: cannot connect to nats

### ISSUE THREAD

**Issue by tzq0301** [testcontainers/testcontainers-go#2037]
### Testcontainers version

0.26.0

### Using the latest Testcontainers version?

Yes

### Host OS

macOS

### Host arch

ARM

### Go version

1.21

### Docker version

```shell
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.3
 Git commit:        afdd53b4e3
 Built:             Thu Oct 26 07:06:42 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/tzq0301/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     /Users/tzq0301/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/tzq0301/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/tzq0301/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     /Users/tzq0301/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/tzq0301/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/tzq0301/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     /Users/tzq0301/.docker/cli-plugins/docker-scout

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 20
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.758GiB
 Name: linuxkit-ca2fe66a2f4e
 ID: f2858dc3-216e-4280-b29c-7190679d6507
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Cannot connect to NATS container in my demo

```go

package main

import (
	"context"
	"fmt"

	"github.com/nats-io/nats.go"
	"github.com/testcontainers/testcontainers-go"
	natscontainer "github.com/testcontainers/testcontainers-go/modules/nats"
)

func main() {
	ctx := context.Background()

	natsContainer := must(natscontainer.RunContainer(ctx,
		testcontainers.WithImage("nats:latest"),
	))
	should(natsContainer.IsRunning())

	nc := must(nats.Connect(fmt.Sprintf("nats://%s:%d", "127.0.0.1", 4222)))  // <- panic here
	should(nc.IsConnected())
}

func must[T any](t T, err error) T {
	if err != nil {
		panic(err)
	}
	return t
}

func should(b bool) {
	if !b {
		panic(b)
	}
}
```

### Relevant log output

```shell
2023/12/21 10:55:54 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.6
  API Version: 1.43
  Operating System: Docker Desktop
  Total Memory: 7944 MB
  Resolved Docker Host: unix:///Users/tzq0301/.docker/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 65fd60c9ac89fa0dcd321709038e3fd52eec27f1389f7a83f83cff0c51a5fb07
  Test ProcessID: 8214f399-4aff-4e2d-ac0a-f27e1723f84b
2023/12/21 10:55:54 🐳 Creating container for image docker.io/testcontainers/ryuk:0.5.1
2023/12/21 10:55:54 ✅ Container created: ccc14d931ff3
2023/12/21 10:55:54 🐳 Starting container: ccc14d931ff3
2023/12/21 10:55:54 ✅ Container started: ccc14d931ff3
2023/12/21 10:55:54 🚧 Waiting for container id ccc14d931ff3 image: docker.io/testcontainers/ryuk:0.5.1. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2023/12/21 10:55:54 🐳 Creating container for image nats:latest
2023/12/21 10:55:54 ✅ Container created: 0aece7fc83ed
2023/12/21 10:55:54 🐳 Starting container: 0aece7fc83ed
2023/12/21 10:55:54 ✅ Container started: 0aece7fc83ed
2023/12/21 10:55:54 🚧 Waiting for container id 0aece7fc83ed image: nats:latest. Waiting for: &{timeout:<nil> Log:Listening for client connections on 0.0.0.0:4222 IsRegexp:false Occurrence:1 PollInterval:100ms}
panic: nats: no servers available for connection

goroutine 1 [running]:
main.must[...](...)
        /Users/tzq0301/Code/Go/nats-demo/pubsub/main.go:26
main.main()
        /Users/tzq0301/Code/Go/nats-demo/pubsub/main.go:20 +0x144
exit status 2
```

**Comment by tzq0301** [comment]
just modified to use `nc := must(nats.Connect(must(natsContainer.ConnectionString(ctx))))`
