### ISSUE TITLE
[Bug]: Can't run cockroachdb test container on CentOS 8 CI machine

### ISSUE THREAD

**Issue by AhmedNSidd** [testcontainers/testcontainers-go#2454]
### Testcontainers version

v0.29.1

### Using the latest Testcontainers version?

Yes

### Host OS

Linux (CentOS)

### Host arch

x86_64

### Go version

1.21

### Docker version

```shell
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:19:04 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:17:57 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    26.0.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.13.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.25.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 0
  Paused: 0
  Stopped: 9
 Images: 72
 Server Version: 26.0.0
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-348.el8.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.586GiB
 Name: [REDACTED]
 ID: cc115563-2735-4377-adc2-9389fa1328b5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  [REDACTED]
  [REDACTED]
  [REDACTED]
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

I ran a simple unit test that was responsible for starting the CockroachDB test container on my CI machine:

```
package cockroach

import (
	"context"
	"github.com/testcontainers/testcontainers-go/modules/cockroachdb"
	"log"
	"testing"
)

func TestStartCockroachDb(t *testing.T) {
	ctx := context.Background()

	cockroachdbContainer, err := cockroachdb.RunContainer(ctx)
	if err != nil {
		log.Fatalf("failed to start container: %s", err)
	}

	// Clean up the container
	defer func() {
		if err := cockroachdbContainer.Terminate(ctx); err != nil {
			log.Fatalf("failed to terminate container: %s", err)
		}
	}()
}
```

But when I ran it, I got the following error: 
```
2024/03/29 15:25:50 failed to start container: failed to start container: context deadline exceeded
exit status 1
FAIL    cockroach      63.608s
```

The thing is, you might think that one just needs to increase the wait strategy's timeout. The first problem is, you can't do that for cockroachdb's testcontainer module ([see this issue](https://github.com/testcontainers/testcontainers-go/issues/2453)). The second problem is that I went into the testcontainer module for cockroachdb's wait strategies, and modified the library file directly out of curiosity. I increased the Startup Timeout to 10 minutes. That STILL didn't make the cockroachdb test container work. I posted the logs for this below. The logs actually produce some interesting output....

Please note, this test is obviously working perfectly fine on my local Mac machine, but just not on my CI...

### Relevant log output

```shell
LOG OUTPUT WITH 10 MINUTE STARTUP TIMEOUT

2024/03/29 15:38:17 🚧 Waiting for container id 15ac00ce3ebc image: cockroachdb/cockroach:latest-v23.1. Waiting for: &{timeout:0xc000014f50 deadline:<nil> Strategies:[0xc0004b6080 0xc000180230]}
panic: test timed out after 10m0s
running tests:
        TestStartCockroachDb (10m0s)

goroutine 310 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x2d

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000007a00, {0xc6db82?, 0x525abc?}, 0xcab2f0)
        /usr/local/go/src/testing/testing.go:1649 +0x3c8
testing.runTests.func1(0x12b91a0?)
        /usr/local/go/src/testing/testing.go:2054 +0x3e
testing.tRunner(0xc000007a00, 0xc00063fc48)
        /usr/local/go/src/testing/testing.go:1595 +0xff
testing.runTests(0xc0002deb40?, {0x12a4620, 0x1, 0x1}, {0x418abf?, 0xc00063fd08?, 0x12b8500?})
        /usr/local/go/src/testing/testing.go:2052 +0x445
testing.(*M).Run(0xc0002deb40)
        /usr/local/go/src/testing/testing.go:1925 +0x636
main.main()
        _testmain.go:47 +0x19c

goroutine 21 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f6bae078e10, 0x72)
        /usr/local/go/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc00053be80?, 0xc000246000?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00053be80, {0xc000246000, 0x2000, 0x2000})
        /usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc00053be80, {0xc000246000?, 0x48aafa?, 0x41bda8?})
        /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00011a1c0, {0xc000246000?, 0x1?, 0x9?})
        /usr/local/go/src/net/net.go:179 +0x45
github.com/jackc/pgx/v5/pgconn/internal/bgreader.(*BGReader).Read(0xc000574ac0, {0xc000246000, 0x2000, 0x2000})
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/internal/bgreader/bgreader.go:100 +0xd7
io.ReadAtLeast({0xd6cbc0, 0xc000574ac0}, {0xc000246000, 0x2000, 0x2000}, 0x5)
        /usr/local/go/src/io/io.go:335 +0x90
github.com/jackc/pgx/v5/pgproto3.(*chunkReader).Next(0xc0002fee70, 0x5)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgproto3/chunkreader.go:80 +0x291
github.com/jackc/pgx/v5/pgproto3.(*Frontend).Receive(0xc000262d80)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgproto3/frontend.go:307 +0x3f
github.com/jackc/pgx/v5/pgconn.(*PgConn).peekMessage(0xc000297200)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/pgconn.go:524 +0x14a
github.com/jackc/pgx/v5/pgconn.(*PgConn).receiveMessage(0xc000297200)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/pgconn.go:544 +0x1c
github.com/jackc/pgx/v5/pgconn.connect({0xd75250, 0xc00023a770}, 0xc0000b9b00, 0xc00052bba0, 0x0)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/pgconn.go:343 +0xd2a
github.com/jackc/pgx/v5/pgconn.ConnectConfig({0xd75250, 0xc00023a770}, 0xc0000b9b00)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/pgconn.go:176 +0x50e
github.com/jackc/pgx/v5.connect({0xd75250, 0xc00023a770}, 0xc0000b9b00)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/conn.go:257 +0x33f
github.com/jackc/pgx/v5.ConnectConfig({0xd75250, 0xc00023a770}, 0xc0000b98c0)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/conn.go:141 +0xf0
github.com/jackc/pgx/v5/stdlib.(*driverConnector).Connect(0xc00031de78, {0xd75250, 0xc00023a770})
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/stdlib/sql.go:365 +0xcd
database/sql.(*DB).conn(0xc000401c70, {0xd75250, 0xc00023a770}, 0x1)
        /usr/local/go/src/database/sql/sql.go:1387 +0x717
database/sql.(*DB).exec(0xc00055ea68?, {0xd75250, 0xc00023a770}, {0xc6695e, 0x8}, {0x0, 0x0, 0x0}, 0x24?)
        /usr/local/go/src/database/sql/sql.go:1651 +0x57
database/sql.(*DB).ExecContext.func1(0x0?)
        /usr/local/go/src/database/sql/sql.go:1634 +0x4f
database/sql.(*DB).retry(0xc0000ff600?, 0xc00055ea60)
        /usr/local/go/src/database/sql/sql.go:1538 +0x42
database/sql.(*DB).ExecContext(0xd75250?, {0xd75250?, 0xc00023a770?}, {0xc6695e?, 0x9?}, {0x0?, 0xc00056ff80?, 0x0?})
        /usr/local/go/src/database/sql/sql.go:1633 +0xc8
github.com/testcontainers/testcontainers-go/wait.(*waitForSql).WaitUntilReady(0xc000180230, {0xd75100?, 0x12e7c40?}, {0x7f6bf6b293c0, 0xc000401790})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/wait/sql.go:112 +0x588
github.com/testcontainers/testcontainers-go/wait.(*MultiStrategy).WaitUntilReady(0xc0004f70b0, {0xd75100?, 0x12e7c40?}, {0x7f6bf6b293c0, 0xc000401790})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/wait/all.go:75 +0x276
github.com/testcontainers/testcontainers-go.glob..func5.1({0xd75100, 0x12e7c40}, {0xd7ff90?, 0xc000401790?})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/lifecycle.go:197 +0x191
github.com/testcontainers/testcontainers-go.(*DockerContainer).startedHook.containerHookFn.func1(...)
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/lifecycle.go:357
github.com/testcontainers/testcontainers-go.(*DockerContainer).startedHook(0xc000401790, {0xd75100?, 0x12e7c40})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/lifecycle.go:250 +0x158
github.com/testcontainers/testcontainers-go.(*DockerContainer).Start(0xc000401790, {0xd75100, 0x12e7c40})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/docker.go:204 +0xe5
github.com/testcontainers/testcontainers-go.GenericContainer({_, _}, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/generic.go:81 +0x404
github.com/testcontainers/testcontainers-go/modules/cockroachdb.RunContainer({0xd75100, 0x12e7c40}, {0x0, 0x0, 0x0?})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go/modules/cockroachdb@v0.29.1/cockroachdb.go:114 +0x4b1
cockroach/cockroach.TestStartCockroachDb(0x0?)
        /cockroach/cockroach_test.go:13 +0x38
testing.tRunner(0xc000007ba0, 0xcab2f0)
        /usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
        /usr/local/go/src/testing/testing.go:1648 +0x3ad

goroutine 60 [chan receive, 9 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1({0xd786d8?, 0xc000002290})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/reaper.go:358 +0x74e
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect in goroutine 21
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/reaper.go:323 +0x185

goroutine 455 [select, 9 minutes]:
github.com/jackc/pgx/v5/pgconn/internal/ctxwatch.(*ContextWatcher).Watch.func1()
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/internal/ctxwatch/context_watcher.go:47 +0x66
created by github.com/jackc/pgx/v5/pgconn/internal/ctxwatch.(*ContextWatcher).Watch in goroutine 21
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/internal/ctxwatch/context_watcher.go:46 +0x11c

goroutine 437 [select, 9 minutes]:
database/sql.(*DB).connectionOpener(0xc000401c70, {0xd751e0, 0xc000535c70})
        /usr/local/go/src/database/sql/sql.go:1218 +0x87
created by database/sql.OpenDB in goroutine 21
        /usr/local/go/src/database/sql/sql.go:791 +0x165
exit status 2
FAIL    cockroach      600.087s
```

**Comment by AhmedNSidd** [comment]
I created another test to run the cockroachdb test container, but this time without using the module:
```
package cockroach

import (
	"context"
	"fmt"
	"github.com/jackc/pgx/v5"
	"github.com/stretchr/testify/require"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
	"log"
	"testing"
)

func TestStartCockroachDb(t *testing.T) {
	ctx := context.Background()

	req := testcontainers.ContainerRequest{
		Image:        "cockroachdb/cockroach:latest-v21.1",
		ExposedPorts: []string{"26257/tcp", "8080/tcp"},
		WaitingFor:   wait.ForHTTP("/health").WithPort("8080"),
		Cmd:          []string{"start-single-node", "--insecure"},
	}
	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: req,
		Started:          true,
	})
	require.NoError(t, err)

	mappedPort, err := container.MappedPort(ctx, "26257")
	require.NoError(t, err)

	hostIP, err := container.Host(ctx)
	require.NoError(t, err)

	uri := fmt.Sprintf("postgres://root@%s:%s", hostIP, mappedPort.Port())

	log.Println(uri)
	dbConn, err := pgx.Connect(ctx, uri)
	require.NoErrorf(t, err, "failed to connect to db in testcontainers: %v", err)

	dbConn.Close(ctx)

	// Clean up the container
	defer func() {
		if err := container.Terminate(ctx); err != nil {
			log.Fatalf("failed to terminate container: %s", err)
		}
	}()
}
```

If you check out the logs, what you'll find really interesting is that it ends up creating the container, but it is unable to connect to the cockroachdb itself, and if you look at the logs, you'll see that the error output seems pretty much the same as the error log output in the test above...

Here are the logs:

```
2024/03/29 15:49:09 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 26.0.0
  API Version: 1.44
  Operating System: CentOS Linux 8
  Total Memory: 7767 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 99a986a4d44903173be2268de95cb8de8c1262947fe7a2251f8ce5e82d6e5365
  Test ProcessID: e085ec81-4cee-41fd-971e-55e247bbfa06
2024/03/29 15:49:09 🐳 Creating container for image testcontainers/ryuk:0.6.0
2024/03/29 15:49:10 ✅ Container created: a21b5bf7e45d
2024/03/29 15:49:10 🐳 Starting container: a21b5bf7e45d
2024/03/29 15:49:11 ✅ Container started: a21b5bf7e45d
2024/03/29 15:49:11 🚧 Waiting for container id a21b5bf7e45d image: testcontainers/ryuk:0.6.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/03/29 15:49:11 🔔 Container is ready: a21b5bf7e45d
2024/03/29 15:49:11 🐳 Creating container for image cockroachdb/cockroach:latest-v21.1
2024/03/29 15:49:11 ✅ Container created: 850d1a01c39c
2024/03/29 15:49:11 🐳 Starting container: 850d1a01c39c
2024/03/29 15:49:11 ✅ Container started: 850d1a01c39c
2024/03/29 15:49:11 🚧 Waiting for container id 850d1a01c39c image: cockroachdb/cockroach:latest-v21.1. Waiting for: &{timeout:<nil> Port:8080 Path:/health StatusCodeMatcher:0x9deb80 ResponseMatcher:0xab82e0 UseTLS:false AllowInsecure:false TLSConfig:<nil> Method:GET Body:<nil> PollInterval:100ms UserInfo: ForceIPv4LocalHost:false}
2024/03/29 15:49:11 🔔 Container is ready: 850d1a01c39c
2024/03/29 15:49:11 postgres://root@localhost:33835
panic: test timed out after 10m0s
running tests:
        TestStartCockroachDb (10m0s)

goroutine 95 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x2d

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000102820, {0xc6543c?, 0x525a3c?}, 0xca3478)
        /usr/local/go/src/testing/testing.go:1649 +0x3c8
testing.runTests.func1(0x12aa420?)
        /usr/local/go/src/testing/testing.go:2054 +0x3e
testing.tRunner(0xc000102820, 0xc0005bfc48)
        /usr/local/go/src/testing/testing.go:1595 +0xff
testing.runTests(0xc0002d0320?, {0x1295520, 0x1, 0x1}, {0x418a3f?, 0xc0005bfd08?, 0x12a9780?})
        /usr/local/go/src/testing/testing.go:2052 +0x445
testing.(*M).Run(0xc0002d0320)
        /usr/local/go/src/testing/testing.go:1925 +0x636
main.main()
        _testmain.go:47 +0x19c

goroutine 8 [IO wait, 10 minutes]:
internal/poll.runtime_pollWait(0x7f67501a4c90, 0x72)
        /usr/local/go/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0005ede80?, 0xc00022f7d0?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0005ede80, {0xc00022f7d0, 0x1, 0x1})
        /usr/local/go/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0005ede80, {0xc00022f7d0?, 0xd6cce0?, 0x45929d?})
        /usr/local/go/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc00006a5f0, {0xc00022f7d0?, 0x7f674273ec40?, 0x7f6798dd0108?})
        /usr/local/go/src/net/net.go:179 +0x45
io.ReadAtLeast({0xd66ac0, 0xc00006a5f0}, {0xc00022f7d0, 0x1, 0x1}, 0x1)
        /usr/local/go/src/io/io.go:335 +0x90
io.ReadFull(...)
        /usr/local/go/src/io/io.go:354
github.com/jackc/pgx/v5/pgconn.startTLS({0xd70278?, 0xc00006a5f0}, 0xc0001c3520)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/pgconn.go:429 +0xdf
github.com/jackc/pgx/v5/pgconn.connect({0xd6cce0, 0x12d8ec0}, 0xc00027aa20, 0xc0005ebb80, 0x0)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/pgconn.go:294 +0x2fd
github.com/jackc/pgx/v5/pgconn.ConnectConfig({0xd6cce0, 0x12d8ec0}, 0xc00027aa20)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/pgconn/pgconn.go:176 +0x50e
github.com/jackc/pgx/v5.connect({0xd6cce0, 0x12d8ec0}, 0xc00027aa20)
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/conn.go:257 +0x33f
github.com/jackc/pgx/v5.Connect({0xd6cce0, 0x12d8ec0}, {0xc00049eb80?, 0xc000127628?})
        /root/go/pkg/mod/github.com/jackc/pgx/v5@v5.5.4/conn.go:121 +0x4a
cockroach.TestStartCockroachDb(0xc0001029c0?)
        cockroach/cockroach_test.go:38 +0x488
testing.tRunner(0xc0001029c0, 0xca3478)
        /usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
        /usr/local/go/src/testing/testing.go:1648 +0x3ad

goroutine 82 [chan receive, 10 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1({0xd70278?, 0xc00006a328})
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/reaper.go:358 +0x74e
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect in goroutine 8
        /root/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.29.1/reaper.go:323 +0x185
exit status 2
FAIL    cockroach      600.096s

```

**Comment by AhmedNSidd** [comment]
I resolved this issue on my own... Well, I didn't resolve it, but I found a workaround. I found out that my CI was using CentOS 8. I moved to a different environment where CentOS 7 was being used, and ran the tests again, and it worked.

I have a theory that this had nothing to do with testcontainers itself, and something was wrong with my CI itself. As such, I'm closing this issue.
