### ISSUE TITLE
Inconsistent test stalling issue

### ISSUE THREAD

**Issue by jackzampolin** [testcontainers/testcontainers-go#313]
**Describe the bug**
Sometimes my tests stall around exit and then the test runner panics with a timeout. This results in the docker daemon needing to be restarted.

**To Reproduce**
repo: `https://github.com/jackzampolin/horcrux/pulls/1`
commands: `go test -v ./testing/...

**Expected behavior**

**Additional context**

Panic
```
panic: test timed out after 10m0s

goroutine 393 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x45

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc000538780, 0x4b4bbec, 0x1d, 0x4ca43f8, 0x4098866)
	/usr/local/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000538600)
	/usr/local/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000538600, 0xc000e5fde0)
	/usr/local/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc00000e6c0, 0x5314910, 0x1, 0x1, 0xc01a3ed4657a40e8, 0x8bb4a175b6, 0x532ebc0, 0x4b3cf4f)
	/usr/local/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc000ca9f80, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x1eb
main.main()
	_testmain.go:43 +0x138

goroutine 67 [chan receive, 8 minutes]:
github.com/jackzampolin/horcrux/testing.startCleanupRoutine.func2()
	/Users/johnzampolin/go/src/github.com/jackzampolin/horcrux/testing/setup_test.go:56 +0x54
testing.(*common).Cleanup.func1()
	/usr/local/go/src/testing/testing.go:901 +0xef
testing.(*common).runCleanup(0xc000538780, 0x0, 0x0, 0x0)
	/usr/local/go/src/testing/testing.go:1007 +0x8c
testing.tRunner.func2(0xc000538780)
	/usr/local/go/src/testing/testing.go:1187 +0x48
testing.tRunner(0xc000538780, 0x4ca43f8)
	/usr/local/go/src/testing/testing.go:1197 +0x10e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3

goroutine 110 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc00120d980, 0x4d98b38, 0xc0005b4258)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 182 [select, 8 minutes]:
net/http.(*persistConn).writeLoop(0xc00144e7e0)
	/usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1744 +0xc9c

goroutine 179 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc00071c540, 0x4d98b38, 0xc000010170)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 23 [chan receive, 10 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc000d18960, 0x4d98b38, 0xc000d045f8)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 15 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc00071d0e0, 0x4d98b38, 0xc0001a6b90)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 16 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc00071c240, 0x4d98b38, 0xc000010138)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 55 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc00053c180, 0x4d98b38, 0xc000548000)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 181 [IO wait, 8 minutes]:
internal/poll.runtime_pollWait(0xd804eb8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000fd6498, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000fd6480, 0xc000f25000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000fd6480, 0xc000f25000, 0x1000, 0x1000, 0x403d4fc, 0xc000d25c38, 0x406c2c0)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010218, 0xc000f25000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc00144e7e0, 0xc000f25000, 0x1000, 0x1000, 0xc00071d1a0, 0xc000d25d40, 0x4007d15)
	/usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc0011be9c0)
	/usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc0011be9c0, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
	/usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc00144e7e0)
	/usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1743 +0xc77

goroutine 99 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0005a00c0, 0x4d98b38, 0xc0005b4008)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 60 [IO wait, 8 minutes]:
internal/poll.runtime_pollWait(0xd804ce8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00053e118, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00053e100, 0xc001141000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc00053e100, 0xc001141000, 0x1000, 0x1000, 0x403d4fc, 0xc001024c38, 0x406c2c0)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000548108, 0xc001141000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc0000f1b00, 0xc001141000, 0x1000, 0x1000, 0xc0011b34a0, 0xc001024d40, 0x4007d15)
	/usr/local/go/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc00010eea0)
	/usr/local/go/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc00010eea0, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
	/usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0000f1b00)
	/usr/local/go/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1743 +0xc77

goroutine 116 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0011b24e0, 0x4d98b38, 0xc0000107b0)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 74 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc000180de0, 0x4d98b38, 0xc0000105d8)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 91 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0010b6840, 0x4d98b38, 0xc00013c170)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 92 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0010b70e0, 0x4d98b38, 0xc00013c1e8)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 121 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0011b2d20, 0x4d98b38, 0xc000010858)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 178 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc00071c3c0, 0x4d98b38, 0xc000010150)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 168 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc000d18a20, 0x4d98b38, 0xc0001a61d8)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 100 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0005a0cc0, 0x4d98b38, 0xc0005b4088)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 115 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc001187740, 0x4d98b38, 0xc000010738)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 132 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0010ccf00, 0x4d98b38, 0xc00013c2e0)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 147 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0013ba960, 0x4d98b38, 0xc0005b4328)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 126 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0011b3740, 0x4d98b38, 0xc0000108d8)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 152 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0013bb380, 0x4d98b38, 0xc0005b43a8)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 163 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc001474180, 0x4d98b38, 0xc000010958)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 219 [chan receive]:
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x532e160)
	/Users/johnzampolin/go/pkg/mod/github.com/rcrowley/go-metrics@v0.0.0-20200313005456-10cdbea86bc0/meter.go:239 +0x3b
created by github.com/rcrowley/go-metrics.NewMeter
	/Users/johnzampolin/go/pkg/mod/github.com/rcrowley/go-metrics@v0.0.0-20200313005456-10cdbea86bc0/meter.go:46 +0x11a

goroutine 227 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc0011861e0, 0x4d98b38, 0xc00013c128)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 226 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc001186060, 0x4d98b38, 0xc00013c110)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 213 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc00014a2a0, 0x4d98b38, 0xc000d04100)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 218 [chan receive, 8 minutes]:
github.com/testcontainers/testcontainers-go.(*Reaper).Connect.func1(0xc000d882d0, 0xc00014a7e0, 0x4d98b38, 0xc000d04138)
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:136 +0x605
created by github.com/testcontainers/testcontainers-go.(*Reaper).Connect
	/Users/johnzampolin/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:108 +0x1a5

goroutine 61 [select, 8 minutes]:
net/http.(*persistConn).writeLoop(0xc0000f1b00)
	/usr/local/go/src/net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1744 +0xc9c
FAIL	github.com/jackzampolin/horcrux/testing	600.053s
FAIL
```

**Comment by mdelapenya** [comment]
@jackzampolin I'm closing this issue as stale. Feel free to reopen it if you see the interest in it.

Thanks for participating in the community 😊 

![image](https://media.giphy.com/media/42YlR8u9gV5Cw/giphy.gif)

**Comment by marshal-f** [comment]
Just wanted to state that I ran into the same issue as @jackzampolin today while following the [quick start guide](https://golang.testcontainers.org/quickstart/). Restarting the docker deamon fixed it for me.

Panic:

`marshal@ubuntu20:~/project$ go test ./...
2024/01/24 15:38:42 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.7
  API Version: 1.43
  Operating System: Ubuntu 20.04.6 LTS
  Total Memory: 15953 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 013c1ae5d7ac1d93908f37eda7ced29fce9e4e1cccb4b618c9cd198836b8eb76
  Test ProcessID: 711e86a5-24e1-4aaf-bfcd-d7c20fef3b26
panic: test timed out after 10m0s
running tests:
	TestWithRedis (10m0s)

goroutine 36 [running]:
testing.(*M).startAlarm.func1()
	/snap/go/10489/src/testing/testing.go:2259 +0x3b9
created by time.goFunc
	/snap/go/10489/src/time/sleep.go:176 +0x2d

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0005004e0, {0xceb419?, 0x52c73c?}, 0xd94100)
	/snap/go/10489/src/testing/testing.go:1649 +0x3c8
testing.runTests.func1(0x1407480?)
	/snap/go/10489/src/testing/testing.go:2054 +0x3e
testing.tRunner(0xc0005004e0, 0xc000609c48)
	/snap/go/10489/src/testing/testing.go:1595 +0xff
testing.runTests(0xc0003f1e00?, {0x13f3000, 0x1, 0x1}, {0x41887f?, 0xc000609d08?, 0x1406100?})
	/snap/go/10489/src/testing/testing.go:2052 +0x445
testing.(*M).Run(0xc0003f1e00)
	/snap/go/10489/src/testing/testing.go:1925 +0x636
main.main()
	_testmain.go:47 +0x19c

goroutine 7 [IO wait, 10 minutes]:
internal/poll.runtime_pollWait(0x7f46d2357e28, 0x72)
	/snap/go/10489/src/runtime/netpoll.go:343 +0x85
internal/poll.(*pollDesc).wait(0xc0000b3000?, 0xc00020f000?, 0x0)
	/snap/go/10489/src/internal/poll/fd_poll_runtime.go:84 +0x27
internal/poll.(*pollDesc).waitRead(...)
	/snap/go/10489/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0000b3000, {0xc00020f000, 0x1000, 0x1000})
	/snap/go/10489/src/internal/poll/fd_unix.go:164 +0x27a
net.(*netFD).Read(0xc0000b3000, {0xc00020f000?, 0xc000283360?, 0x0?})
	/snap/go/10489/src/net/fd_posix.go:55 +0x25
net.(*conn).Read(0xc000112778, {0xc00020f000?, 0x0?, 0x0?})
	/snap/go/10489/src/net/net.go:179 +0x45
net/http.(*persistConn).Read(0xc0001ec6c0, {0xc00020f000?, 0xc0002834d0?, 0x9d6065?})
	/snap/go/10489/src/net/http/transport.go:1954 +0x4a
bufio.(*Reader).fill(0xc0004998c0)
	/snap/go/10489/src/bufio/bufio.go:113 +0x103
bufio.(*Reader).ReadSlice(0xc0004998c0, 0xe0?)
	/snap/go/10489/src/bufio/bufio.go:379 +0x29
net/http/internal.readChunkLine(0xc00023a0b0?)
	/snap/go/10489/src/net/http/internal/chunked.go:156 +0x1c
net/http/internal.(*chunkedReader).beginChunk(0xc00023a090)
	/snap/go/10489/src/net/http/internal/chunked.go:49 +0x25
net/http/internal.(*chunkedReader).Read(0xc00023a090, {0xc00031025d?, 0x426e1c?, 0x143a100?})
	/snap/go/10489/src/net/http/internal/chunked.go:125 +0x133
net/http.(*body).readLocked(0xc000178300, {0xc00031025d?, 0xc000283648?, 0x4126fd?})
	/snap/go/10489/src/net/http/transfer.go:839 +0x3b
net/http.(*body).Read(0xc0002836b8?, {0xc00031025d?, 0x380?, 0x0?})
	/snap/go/10489/src/net/http/transfer.go:831 +0x118
net/http.(*bodyEOFSignal).Read(0xc000178340, {0xc00031025d, 0x123, 0x123})
	/snap/go/10489/src/net/http/transport.go:2810 +0x13f
io.ReadAll({0xe596e0, 0xc000178340})
	/snap/go/10489/src/io/io.go:704 +0x7e
github.com/testcontainers/testcontainers-go.(*DockerProvider).attemptToPullImage(0xc0001fec30, {0xe5ddd8, 0xc000296c00}, {0xcf3cb4, 0x19}, {0x0, {0xc000300370, 0xa4}, 0x0, {0x0, ...}})
	/home/marshal/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.27.0/docker.go:1188 +0x27d
github.com/testcontainers/testcontainers-go.(*DockerProvider).CreateContainer(_, {_, _}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
	/home/marshal/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.27.0/docker.go:968 +0x139d
github.com/testcontainers/testcontainers-go.(*DockerProvider).RunContainer(_, {_, _}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
	/home/marshal/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.27.0/docker.go:1203 +0x59
github.com/testcontainers/testcontainers-go.newReaper({0xe5ddd8, 0xc000296c00}, {0xc00048cb40, 0x40}, {0xe5b0b0?, 0xc0001fec30})
	/home/marshal/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.27.0/reaper.go:252 +0x758
github.com/testcontainers/testcontainers-go.reuseOrCreateReaper.func1()
	/home/marshal/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.27.0/reaper.go:172 +0x38
sync.(*Once).doSlow(0xe5dd30?, 0x1438540?)
	/snap/go/10489/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
	/snap/go/10489/src/sync/once.go:65
github.com/testcontainers/testcontainers-go.reuseOrCreateReaper({0xe5ddd8?, 0xc000296c00}, {0xc00048cb40, 0x40}, {0xe5b0b0?, 0xc0001fec30})
	/home/marshal/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.27.0/reaper.go:171 +0x22c
github.com/testcontainers/testcontainers-go.(*DockerProvider).CreateContainer(_, {_, _}, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
	/home/marshal/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.27.0/docker.go:880 +0x5ec
github.com/testcontainers/testcontainers-go.GenericContainer({_, _}, {{{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...}, ...})
	/home/marshal/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.27.0/generic.go:74 +0x2b1
bitbucket.org/test-project.TestWithRedis(0x0?)
	/home/marshal/project/clickhouse_test.go:18 +0x166
testing.tRunner(0xc000500680, 0xd94100)
	/snap/go/10489/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	/snap/go/10489/src/testing/testing.go:1648 +0x3ad

goroutine 15 [select, 10 minutes]:
net/http.(*persistConn).readLoop(0xc0001ec6c0)
	/snap/go/10489/src/net/http/transport.go:2238 +0xd25
created by net/http.(*Transport).dialConn in goroutine 14
	/snap/go/10489/src/net/http/transport.go:1776 +0x169f

goroutine 16 [select, 10 minutes]:
net/http.(*persistConn).writeLoop(0xc0001ec6c0)
	/snap/go/10489/src/net/http/transport.go:2421 +0xe5
created by net/http.(*Transport).dialConn in goroutine 14
	/snap/go/10489/src/net/http/transport.go:1777 +0x16f1
FAIL	bitbucket.org/test-project	600.179s
FAIL
`
