### ISSUE TITLE
Intermittent panic for GenericContainer Started true

### ISSUE THREAD

**Issue by mchlstckl** [testcontainers/testcontainers-go#318]
**Describe the bug**
Sometimes, when we run our tests, the following panic happens.
```
=== RUN   TestServerEndpoints
2021/05/07 13:36:26 Starting container id: 96a710e8a466 image: quay.io/testcontainers/ryuk:0.2.3
2021/05/07 13:36:27 Waiting for container id 96a710e8a466 image: quay.io/testcontainers/ryuk:0.2.3
--- FAIL: TestServerEndpoints (1.50s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 10 [running]:
testing.tRunner.func1.2(0x1cd6f00, 0xc000566750)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000582780)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1146 +0x4b6
panic(0x1cd6f00, 0xc000566750)
	/usr/local/Cellar/go/1.16.3/libexec/src/runtime/panic.go:965 +0x1b9
github.com/testcontainers/testcontainers-go.(*DockerContainer).MappedPort(0xc000214580, 0x1f1c180, 0xc00021e360, 0x1d5742a, 0x8, 0x0, 0x0, 0x3132303200000000, 0x63)
	/Users/michael/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:133 +0x485
github.com/testcontainers/testcontainers-go/wait.(*HostPortStrategy).WaitUntilReady(0xc00000eeb8, 0x1f1c148, 0xc00021e360, 0x1f1c500, 0xc000214580, 0x0, 0x0)
	/Users/michael/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/wait/host_port.go:59 +0x16f
github.com/testcontainers/testcontainers-go.(*DockerContainer).Start(0xc000214580, 0x1f1c148, 0xc000038150, 0x0, 0x0)
	/Users/michael/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:165 +0x315
github.com/testcontainers/testcontainers-go.(*DockerProvider).RunContainer(0xc00030da70, 0x1f1c148, 0xc000038150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1d71b94, ...)
	/Users/michael/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:727 +0xeb
github.com/testcontainers/testcontainers-go.NewReaper(0x1f1c148, 0xc000038150, 0xc0001fa840, 0x24, 0x1f04780, 0xc00030da70, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/michael/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/reaper.go:78 +0x455
github.com/testcontainers/testcontainers-go.(*DockerProvider).CreateContainer(0xc00030da70, 0x1f1c148, 0xc000038150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1d602c4, ...)
	/Users/michael/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/docker.go:534 +0x18c8
github.com/testcontainers/testcontainers-go.GenericContainer(0x1f1c148, 0xc000038150, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1d602c4, 0x12, ...)
	/Users/michael/go/pkg/mod/github.com/testcontainers/testcontainers-go@v0.10.0/generic.go:43 +0xb5
gitlab.com/instabox/geospatial-api-go/internal/spaces.TestSpacesContainer(0x1f27568, 0xc000582780, 0x1f1c148, 0xc000038150, 0x1057b39)
	/Users/michael/C/geospatial-api-go/internal/spaces/testing.go:56 +0x43c
gitlab.com/instabox/geospatial-api-go/internal/server.TestServerEndpoints(0xc000582780)
	/Users/michael/C/geospatial-api-go/internal/server/server_test.go:29 +0x93
testing.tRunner(0xc000582780, 0x1d9a660)
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/Cellar/go/1.16.3/libexec/src/testing/testing.go:1238 +0x2b3
```

**To Reproduce**
This only happens sometimes. But the way we start testcontainers is as follows:
```
healthPort, err := nat.NewPort("tcp", "9000")
if err != nil {
    t.Error(err)
}

req := testcontainers.ContainerRequest{
    Image:        "minio/minio:latest",
    ExposedPorts: []string{"9000/tcp"},
    WaitingFor:   wait.ForHTTP("/minio/health/live").WithPort(healthPort),
    Env: map[string]string{
        "MINIO_ACCESS_KEY": accessKey,
        "MINIO_SECRET_KEY": secretKey,
    },
    Entrypoint: []string{"sh"},
    Cmd:        []string{"-c", fmt.Sprintf("mkdir -p /data/%s && /usr/bin/minio server /data", bucket)},
}

container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
    ContainerRequest: req,
    Started:          true,
})
if err != nil {
    t.Error(err)
}
```

**Expected behavior**
No panic

**docker info**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 41
  Running: 9
  Paused: 0
  Stopped: 32
 Images: 30
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.775GiB
 Name: docker-desktop
 ID: P3K6:ZIWA:M253:S5ZC:5C3W:YLXX:JULE:NAYJ:YLND:VXSW:KBIO:HTXX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional context**
MacOS 11.2.1

**Comment by butuzov** [comment]
You can close this in favor of #294
