### ISSUE TITLE
[Bug]: Go get fails on `panic: internal error: can't find reason for requirement on github.com/moby/sys/mountinfo@v0.6.0`

### ISSUE THREAD

**Issue by doron-cohen** [testcontainers/testcontainers-go#705]
### Testcontainers version

0.16.0

### Using the latest Testcontainers version?

Yes

### Host OS

Mac

### Host arch

ARM

### Go version

1.18

### Docker version

```shell
Irrelevant
```

### Docker info

```shell
Irrelevant
```

### What happened?

Upgrading from 0.12.0 to latest fails on panic.

### Relevant log output

```shell
❯ go get github.com/testcontainers/testcontainers-go
go: downloading github.com/testcontainers/testcontainers-go v0.16.0
go: downloading github.com/compose-spec/compose-go v1.6.0
go: downloading github.com/docker/cli v20.10.19+incompatible
go: downloading github.com/docker/compose/v2 v2.12.2
go: downloading github.com/docker/docker v20.10.19+incompatible
go: downloading github.com/moby/term v0.0.0-20220808134915-39b0c02b01ae
go: downloading github.com/opencontainers/image-spec v1.0.3-0.20220303224323-02efb9a75ee1
go: downloading golang.org/x/sync v0.1.0
go: downloading golang.org/x/sys v0.1.0
go: downloading github.com/sirupsen/logrus v1.9.0
go: downloading github.com/distribution/distribution/v3 v3.0.0-20220907155224-78b9c98c5c31
go: downloading github.com/hashicorp/go-version v1.6.0
go: downloading github.com/docker/buildx v0.9.1
go: downloading github.com/moby/buildkit v0.10.4
go: downloading k8s.io/client-go v0.24.1
go: downloading github.com/theupdateframework/notary v0.7.0
go: downloading github.com/imdario/mergo v0.3.13
go: downloading github.com/mattn/go-shellwords v1.0.12
go: downloading k8s.io/api v0.24.1
go: downloading k8s.io/apimachinery v0.24.1
go: downloading go.opentelemetry.io/otel/trace v1.11.1
go: downloading go.opentelemetry.io/otel v1.11.1
go: downloading github.com/golang/mock v1.6.0
go: downloading github.com/AlecAivazis/survey/v2 v2.3.6
go: downloading github.com/buger/goterm v1.0.4
go: downloading github.com/gofrs/flock v0.8.0
go: downloading github.com/fvbommel/sortorder v1.0.2
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/xeipuuv/gojsonschema v1.2.0
go: downloading github.com/tonistiigi/units v0.0.0-20180711220420-6950e57a87ea
go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.29.0
go: downloading github.com/tonistiigi/fsutil v0.0.0-20220930225714-4638ad635be5
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.4.1
go: downloading go.opentelemetry.io/otel/sdk v1.4.1
go: downloading github.com/containerd/typeurl v1.0.2
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace v0.29.0
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.29.0
go: downloading github.com/pelletier/go-toml v1.9.4
go: downloading github.com/serialx/hashring v0.0.0-20190422032157-8b2912629002
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.4.1
go: downloading go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.4.1
go: downloading github.com/docker/go v1.5.1-1.0.20160303222718-d30aec9fd63c
go: downloading k8s.io/klog/v2 v2.60.1
go: downloading k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
go: downloading github.com/tonistiigi/vt100 v0.0.0-20210615222946-8066bb97264f
go: downloading github.com/docker/docker-credential-helpers v0.6.4
go: downloading github.com/moby/sys/symlink v0.2.0
go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/gogo/googleapis v1.4.1
go: downloading github.com/moby/sys/signal v0.7.0
go: downloading go.opentelemetry.io/proto/otlp v0.12.0
go: downloading github.com/moby/locker v1.0.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/miekg/pkcs11 v1.1.1
go: downloading sigs.k8s.io/structured-merge-diff/v4 v4.2.1
go: downloading golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8
go: downloading go.opentelemetry.io/otel/metric v0.27.0
go: downloading go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.4.1
go: downloading github.com/moby/patternmatcher v0.5.0
go: downloading sigs.k8s.io/structured-merge-diff v0.0.0-20190525122527-15d366b2352e
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
go: downloading k8s.io/kube-openapi v0.0.0-20201113171705-d219536bb9fd
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading github.com/docker/go-metrics v0.0.1
go: downloading github.com/containerd/ttrpc v1.1.0
go: downloading github.com/moby/spdystream v0.2.0
go: downloading github.com/grpc-ecosystem/grpc-gateway v1.16.0
go: downloading google.golang.org/appengine v1.6.7
go: downloading go.opentelemetry.io/otel/internal/metric v0.27.0
go: downloading github.com/prometheus/client_golang v1.12.2
go: downloading github.com/prometheus/common v0.32.1
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2
go: downloading github.com/googleapis/gnostic v0.5.5
go: downloading github.com/moby/sys/mount v0.3.0
go: downloading github.com/google/gnostic v0.5.7-v3refs
go: downloading sigs.k8s.io/json v0.0.0-20211208200746-9f7c6b3444d2
go: downloading k8s.io/kube-openapi v0.0.0-20220328201542-3ee0da9b0b42
go: downloading github.com/moby/sys/mountinfo v0.6.0
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
go: downloading github.com/go-openapi/swag v0.19.14
go: downloading github.com/go-openapi/jsonreference v0.19.5
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: downloading github.com/tonistiigi/go-rosetta v0.0.0-20220804170347-3f4430f2d346
go: downloading github.com/docker/docker v20.10.22+incompatible
panic: internal error: can't find reason for requirement on github.com/moby/sys/mountinfo@v0.6.0

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0x1400155d3a0?, 0x1400053f710?}, {0x140000e7d00?, 0x14000b35ce8?}})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0xf8
cmd/go/internal/modget.(*resolver).updateBuildList(0x140004aa300, {0x104d0f8b0, 0x140000280a0}, {0x140002b0860, 0x1, 0x1})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x460
cmd/go/internal/modget.(*resolver).applyUpgrades(0x140004aa300, {0x104d0f8b0, 0x140000280a0}, {0x140012cad20?, 0x1?, 0x104cf5440?})
        /usr/local/go/src/cmd/go/internal/modget/get.go:1312 +0xc4
cmd/go/internal/modget.runGet({0x104d0f8b0, 0x140000280a0}, 0x14000030348?, {0x140000201d0, 0x1, 0x1})
        /usr/local/go/src/cmd/go/internal/modget/get.go:351 +0x3c8
main.invoke(0x104fddb60, {0x140000201c0, 0x2, 0x2})
        /usr/local/go/src/cmd/go/main.go:218 +0x2b0
main.main()
        /usr/local/go/src/cmd/go/main.go:175 +0x770
```

**Comment by mdelapenya** [comment]
Hi @doron-cohen have you read the release notes on the replace directives needed for 0.16.0? There we explain the reasons for those replacements

**Comment by mdelapenya** [comment]
Relates to #634

**Comment by doron-cohen** [comment]
Now I see it. Maybe it's worth to put it in the README file. Thanks.

**Comment by mdelapenya** [comment]
OTOH please take a look at #650, where we reduce the dependencies affected by those transitive dependencies with compose

**Comment by mdelapenya** [comment]
Both #706 and #650  were merged, please let us know if the dependency management is clear enough 🙏

**Comment by doron-cohen** [comment]
Thanks @mdelapenya for the responses. I managed to install the dependencies and solve it. I recently tried to move to the Docker Compose API to have our test containers spin up faster but had some issues. Once I get back to that task I will open a new ticket with my findings.
